### ISSUE TITLE
Initial migration does not work

### ISSUE THREAD

**Issue by wesobi** [openknowledgebe/AppsForX#1]
When running php artisan october:up for the first time, it will not work due to a field not being nullable, while it should be.

AppsForX/plugins/rainlab/blog/updates/create_posts_table.php
$table->integer('event_id')->nullable();

**Comment by wesobi** [comment]
While the previous commit made it so that the migration error is gone, I will need to update the **readme.md** file to make sure all necessary steps are taken before running  `php artisan october:up` so you don't have any issues beforehand or a database that is filled up half before getting an error and the other half not migrating.

Going to make a branch specifically for this and put imake a pull request once the previous pull request is accepted.

**Comment by wesobi** [comment]
Add the folders that are missing according to #2 in the **readme** "set-up" guide.

**Comment by pietercolpaert** [comment]
Is this fixed?

**Comment by wesobi** [comment]
Yes, completely. Users just need to be sure the folders exist and are writeable (as said in the readme.md)
